require:
  - rubocop-rails
  
AllCops:
    TargetRubyVersion: 2.6
    Exclude:
        - 'db/migrate/**/*'
        - 'db/schema.rb'
        - 'db/seeds.rb'
        - 'bin/**/*'
        - 'vendor/**/*'
        - 'config/puma.rb'

Rails:
    Enabled: true

Rails/FilePath:
  Enabled: false

Rails/HasManyOrHasOneDependent:
    Exclude:
        - 'app/models/api/*'

Bundler/OrderedGems:
    Enabled: false

Style/RedundantBegin:
    Exclude:
        - 'lib/active_storage/service/s3_with_metadata_service.rb'

Style/Alias:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/NumericLiterals:
    Enabled: false

Style/TrailingCommaInArrayLiteral:
    Enabled: false

Style/TrailingCommaInHashLiteral:
    Enabled: false

Style/TrailingCommaInArguments:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/DoubleNegation:
    Enabled: false

Style/WordArray:
    Enabled: false

Style/ClassAndModuleChildren:
    Enabled: false

Layout/TrailingEmptyLines:
    Enabled: true

Metrics/ClassLength:
    Enabled: false

Metrics/MethodLength:
    Max: 50
    Exclude:

Metrics/ModuleLength:
    Description: 'Avoid modules longer than 250 lines of code.'
    Max: 250

Metrics/AbcSize:
    Max: 25 # TODO: Restore to '20'
    Exclude:
        - 'spec/**/*'

Metrics/LineLength:
    Max: 120

Metrics/BlockLength:
    Max: 40
    Exclude:
        - 'spec/**/*'

Lint/UnusedMethodArgument:
    AllowUnusedKeywordArguments: false
    Exclude:
        - 'config/initializers/active_storage_patch.rb'
        - 'lib/active_storage/**/*'
