language: ruby
rvm:
- 2.6.6
services:
  - postgresql
addons:
  postgresql: "10"
apt:
  packages:
  - postgresql-10
  - postgresql-client-10
dist: xenial
cache:
  - bundler
env:
  matrix:
    - API_ROOT='https://ccs.api/'
  global:
    - CF_USER=ccs-rmi-travis-deploy@crowncommercial.gov.uk
    - CF_ORG=ccs-report-management-info
    - secure: "TVczDk+hUfpUVZ8ns6L5JnECCpow6oOlfGGsQkFrlp4ddUDJoura4t7mbjqREfBevGAsnLGj76RI6GsDUiifWPW6JURQlqJJ2sXW2zwsIIZQUnYJkG0cIgNgBUnySc9pYqS2d2p94XHrtvPHcpcEBMTiInd+di6bTinWujUs3tH65IQI8UTNFpUHGInPQvB79g5K449uUSURBnU4jJZFurDH8IUAXPYnZHZALRDE7ddrIz/UXI4OMPj9BGtkRJUIcWGfrhHCp+CKATF1W3ODQZ2mWtd8FNrpaMkqOLwJkdoOf+JpwXRa7gzxUz7Ck4rnT4FXgutYmNx3p7pXRiFmSPJCe4xTvbA7onvGiAqZTm20V9xSP9rQiHWk6hPw8mEoVT+Itn+nE/cdGiiahylcOCBsDLcEBDgsk3TAba2BoTAWMpAFQqya2tV2LlvR3G+/WuIBx/7RJMfuSR8JyU2Vm53tEL3e8Ve7r22bmslb6rcRBnPuymurWL/LTGIhEYDl6Jdn185wBpE20/PLxFLBKdCzrRPvuQL9hAnK8wLVCENuzg+ux75ockn0B3hQ/Binh40V3w70fW6b1W0tTCSqEh2WfkqYD8UkAi4oQRGa8kq0tBWnI9SjGw+sM+PGPgxTZNJoy/ClOXPN9wY9xhFe5iGrDX8ZTq/M1122B4mVj7c="
    - CC_TEST_REPORTER_ID=fd77fd608d62b7a46467dfa4c8d3ece86f525be4fec94d4874f3ab7665f70693
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64  > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - bundle exec bin/rails db:migrate RAILS_ENV=test
  - bundle exec rake AWS_ACCESS_KEY_ID=dummy AWS_SECRET_ACCESS_KEY=dummy AWS_S3_REGION=dummy AWS_S3_BUCKET=dummy SECRET_KEY_BASE=dummy DATABASE_URL=postgresql:does_not_exist --quiet assets:precompile
before_deploy:
  - echo "install cloudfoundry cli"
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update -qq
  - sudo apt-get install cf7-cli
deploy:
  - provider: script
    script: bash CF/deploy-app.sh -u $CF_USER -o $CF_ORG -p $CF_PASS -s staging
    on:
      branch: develop
  - provider: script
    script: bash CF/deploy-app.sh -u $CF_USER -o $CF_ORG -p $CF_PASS -s conclave-development
    on:
      branch: conclave
  - provider: script
    script: bash CF/deploy-app.sh -u $CF_USER -o $CF_ORG -p $CF_PASS -s prod
    on:
      branch: master
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT