language: ruby
rvm:
- 2.5.7
services:
  - postgresql
addons:
  postgresql: "10"
apt:
  packages:
  - postgresql-10
  - postgresql-client-10
dist: xenial
cache:
  - bundler
env:
  matrix:
    - API_ROOT='https://ccs.api/'
  global:
    - CF_USER=ccs-rmi-travis-deploy@crowncommercial.gov.uk
    - CF_ORG=ccs-report-management-info
    - secure: "TjlSfA/LLvTtCTzyTqP6oUFEkKLFlMJdAs53DjnxcGlSM4WzTWGVbyiVF8VzjmSzjTlZ9WwMn9cvnvRrctHfntGRBtxCfEIY+rPfFGQdokn3ri1GLBC4tO+8U3myBfEwTc4UJQKjPT+KyvaP6aAu6McSjGO6kMl0DSezBpRwOY3rylqGmYa/DAY3YBSsbtyB2OnpT68n5pAQLg2Fd57IRJEeSIuRYQPuuFkTnRTBvalVYsW0n07ubB7/R+RSS636VM71BLZpr1LiHAuEgXR7mWbWHpMnWCjOhyKdmzqfnFLbesuh3o7m8eH54l+vEluT0eTm6jej/ufgURkSw1yAPXHJqdWYJuZpn1BRow0Il0Edu7CfoPf3Uhafa8bR0XTCN2ME0TUKWdbUhDGFGLuUkxCvRBrWKEVQhDeVaakJ0Gt7Fx191UrfvqZLONYKzVEu1+1UT0AOzNztzm9ciANopUkS+fq5foWFUyBwl5/Qaj+sNJ/ZO38JJHut6BajPJsLRT97mnuYtq6VtZ4ZGjtvKt4wRUxyEujc7wd8i2NnY+w+fBnvkexJsofzl4j9s2p8yO/wQiNw7ZNQpsoLKmo3QnaoTyi7eIz1tLZl9kuqL3nNkQb9UzFFsqsxno0M+7tnevhhmSpiO6PwGU2a8EhUKGZAMkx6BYkpRVG/cJqPQ/w="
before_script:
  - bundle exec bin/rails db:migrate RAILS_ENV=test
  - bundle exec rake AWS_ACCESS_KEY_ID=dummy AWS_SECRET_ACCESS_KEY=dummy AWS_S3_REGION=dummy AWS_S3_BUCKET=dummy SECRET_KEY_BASE=dummy DATABASE_URL=postgresql:does_not_exist --quiet assets:precompile
before_deploy:
  - echo "install cloudfoundry cli"
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update -qq
  - sudo apt-get install cf-cli
  - cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
  - cf install-plugin blue-green-deploy -f -r CF-Community
deploy:
  - provider: script
    script: bash CF/deploy-app.sh -u $CF_USER -o $CF_ORG -p $CF_PASS -s staging
    on:
      branch: develop
  - provider: script
    script: bash CF/deploy-app.sh -u $CF_USER -o $CF_ORG -p $CF_PASS -s prod
    on:
      branch: master
