---
version: '3'
services:
  web:
    build:
      context: .
      args:
        RAILS_ENV: "development"
    ports: ["3100:3100"]
    environment:
      RAILS_ENV: "development"
    env_file:
      - docker-compose.env
    depends_on:
      - db
    tty: true
    stdin_open: true
    restart: on-failure
    volumes:
      - .:/srv/dss:cached
    command: bash -c "rm -f tmp/pids/server.pid && rails s"
    container_name: "data-submission-service_web"

  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/:cached
    restart: on-failure
    container_name: "data-submission-service_db"

volumes:
  pg_data: {}
