Rails.application.config.xray = {
  # default segment name generated by XRay middleware
  name: 'apm_rmi',
  patch: %I[net_http aws_sdk],
  # record db transactions as subsegments
  active_record: true
}
