Date::DATE_FORMATS[:default] = '%e %B %Y'
Date::DATE_FORMATS[:month_year] = '%B %Y'
Date::DATE_FORMATS[:invoice_date] = '%d/%m/%Y'
Time::DATE_FORMATS[:invoice_date] = '%d/%m/%Y'
Time::DATE_FORMATS[:default] = '%e %B %Y'
Time::DATE_FORMATS[:date_with_utc_time] = '%e %B %Y %H:%M %Z'
